---
development:
  adapter: 'sqlite3'
  database: 'db/ads.sqlite3'
  status: 'current'
  twitter:
    hash_tag: '#DvwbW5'
    consumer_key: '1xVQOfhP4eeuwDagASXSBqEbP'
    consume_secret: 'T7Fp4HFNAoTJZCBajS3thpLrQzwZtb0fB6pgPOCANczLjEgKiN'
    access_token: '135599641-fatv1Mg1tpAmtbkVBeLJGJ5S78VZOzRvYGFrhsVt'
    access_token_secret: 'qslzkmeo1PZk2AjImfzgYjwNTnXdV29wIjsTCf6DAicf8'
test:
  adapter: 'sqlite3'
  database: 'db/ads.sqlite3'
  status: 'none'
  twitter:
    hash_tag: '#DvwbW5'
    consumer_key: '1xVQOfhP4eeuwDagASXSBqEbP'
    consume_secret: 'T7Fp4HFNAoTJZCBajS3thpLrQzwZtb0fB6pgPOCANczLjEgKiN'
    access_token: '135599641-fatv1Mg1tpAmtbkVBeLJGJ5S78VZOzRvYGFrhsVt'
    access_token_secret: 'qslzkmeo1PZk2AjImfzgYjwNTnXdV29wIjsTCf6DAicf8'
production:
  adapter: 'sqlite3'
  database: 'ads'
  status: 'none'
  twitter:
    hash_tag: '#trucks'
    consumer_key: '1xVQOfhP4eeuwDagASXSBqEbP'
    consume_secret: 'T7Fp4HFNAoTJZCBajS3thpLrQzwZtb0fB6pgPOCANczLjEgKiN'
    access_token: '135599641-fatv1Mg1tpAmtbkVBeLJGJ5S78VZOzRvYGFrhsVt'
    access_token_secret: 'qslzkmeo1PZk2AjImfzgYjwNTnXdV29wIjsTCf6DAicf8'
